// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    return $.get('https://api.github.com/repos/alexmakers/authentication_demo/issues', function(issues) {
      return $.each(issues, function(index, issue) {
        return $('#issues').append($('<li />', {
          text: issue.title
        }));
      });
    });
  });

}).call(this);
